typedef enum /* @enum$101main_story_c */ {
    GFX_NULL = 0,
    GFX_STORY = 1,
    GFX_TITLE = 2,
    GFX_MANUAL = 3,
    GFX_GAME = 4,
    GFX_MENU = 5,
    GFX_TECHMES = 6,
    GFX_BOOT_ERROR = 7,
} @enum$101main_story_c;
typedef enum /* @enum$98dm_title_main_c */ {
    MAIN_11 = 0,
    MAIN_12 = 1,
    MAIN_STORY = 2,
    MAIN_TITLE = 3,
    MAIN_MANUAL = 4,
    MAIN_GAME = 5,
    MAIN_MENU = 6,
    MAIN_TECHMES = 7,
    MAIN_CONT_ERROR = 8,
    MAIN_TV_ERROR = 9,
    MAIN_CSUM_ERROR = 10,
    MAIN_MEMORYCARD_CHECK = 11,
} @enum$98dm_title_main_c;
typedef enum /* @enum$106dm_title_main_c */ {
    GSL_1PLAY = 0,
    GSL_2PLAY = 1,
    GSL_4PLAY = 2,
    GSL_VSCPU = 3,
    GSL_1DEMO = 4,
    GSL_2DEMO = 5,
    GSL_4DEMO = 6,
    GSL_MAX = 7,
} @enum$106dm_title_main_c;
typedef enum /* @enum$107dm_title_main_c */ {
    GMD_NORMAL = 0,
    GMD_FLASH = 1,
    GMD_TaiQ = 2,
    GMD_TIME_ATTACK = 3,
} @enum$107dm_title_main_c;
typedef enum /* @enum$110dm_title_main_c */ {
    false = 0,
    true = 1,
} @enum$110dm_title_main_c;
typedef enum /* @enum$99dm_game_main_c */ {
    dm_mode_null = 0,
    dm_mode_init = 1,
    dm_mode_wait = 2,
    dm_mode_throw = 3,
    dm_mode_down = 4,
    dm_mode_down_wait = 5,
    dm_mode_erase_chack = 6,
    dm_mode_erase_anime = 7,
    dm_mode_ball_down = 8,
    dm_mode_cap_set = 9,
    dm_mode_stage_clear = 10,
    dm_mode_game_over = 11,
    dm_mode_bottom_up = 12,
    dm_mode_win = 13,
    dm_mode_win_retry = 14,
    dm_mode_lose = 15,
    dm_mode_lose_retry = 16,
    dm_mode_draw = 17,
    dm_mode_draw_retry = 18,
    dm_mode_tr_chaeck = 19,
    dm_mode_training = 20,
    dm_mode_tr_erase_chack = 21,
    dm_mode_tr_cap_set = 22,
    dm_mode_pause = 23,
    dm_mode_pause_retry = 24,
    dm_mode_no_action = 25,
    dm_mode_clear_wait = 26,
    dm_mode_clear_result = 27,
    dm_mode_gover_wait = 28,
    dm_mode_gover_result = 29,
    dm_mode_retire_wait = 30,
    dm_mode_retire_result = 31,
    dm_mode_debug_config = 32,
    dm_mode_debug = 33,
} @enum$99dm_game_main_c;
typedef enum /* @enum$98dm_game_main_c */ {
    dm_cnd_null = 0,
    dm_cnd_wait = 1,
    dm_cnd_init = 2,
    dm_cnd_stage_clear = 3,
    dm_cnd_game_over = 4,
    dm_cnd_win = 5,
    dm_cnd_win_retry = 6,
    dm_cnd_win_retry_sc = 7,
    dm_cnd_lose = 8,
    dm_cnd_lose_retry = 9,
    dm_cnd_lose_retry_sc = 10,
    dm_cnd_draw = 11,
    dm_cnd_draw_retry = 12,
    dm_cnd_pause = 13,
    dm_cnd_pause_re = 14,
    dm_cnd_pause_re_sc = 15,
    dm_cnd_retire = 16,
    dm_cnd_tr_chack = 17,
    dm_cnd_training = 18,
    dm_cnd_clear_wait = 19,
    dm_cnd_clear_result = 20,
    dm_cnd_gover_wait = 21,
    dm_cnd_gover_result = 22,
    dm_cnd_retire_wait = 23,
    dm_cnd_retire_result = 24,
    dm_cnd_debug_config = 25,
    dm_cnd_debug = 26,
} @enum$98dm_game_main_c;
typedef enum /* @enum$100dm_game_main_c */ {
    dm_ret_game_end = -2,
    dm_ret_game_over = -1,
    dm_ret_null = 0,
    dm_ret_next_stage = 1,
    dm_ret_retry = 2,
    dm_ret_virus_wait = 3,
    dm_ret_pause = 4,
    dm_ret_black_up = 5,
    dm_ret_clear = 6,
    dm_ret_tr_a = 7,
    dm_ret_tr_b = 8,
    dm_ret_replay = 9,
    dm_ret_end = 100,
} @enum$100dm_game_main_c;
typedef enum /* @enum$362record_c */ {
    _1P_STORY = 0,
    _1P_LEVEL = 1,
    _1P_TaiQ = 2,
    _1P_TimeAt = 3,
} @enum$362record_c;
typedef enum /* @enum$494record_c */ {
    _VS_COM = 0,
    _VS_COM_FLASH = 1,
    _VS_MAN = 2,
    _VS_MAN_FLASH = 3,
    _VS_MAN_TIME_AT = 4,
} @enum$494record_c;
typedef enum /* @enum$856main_menu_c */ {
    MODE_MAIN = 0,
    MODE_PLAY1 = 1,
    MODE_STORY_NS = 2,
    MODE_STORY_NE = 3,
    MODE_STORY = 4,
    MODE_LVSEL_NS = 5,
    MODE_LVSEL_NE = 6,
    MODE_LVSEL = 7,
    MODE_LVSEL_TQ_NS = 8,
    MODE_LVSEL_TQ_NE = 9,
    MODE_LVSEL_TQ = 10,
    MODE_LVSEL_TA_NS = 11,
    MODE_LVSEL_TA_NE = 12,
    MODE_LVSEL_TA = 13,
    MODE_VSCOM_NS = 14,
    MODE_VSCOM_NE = 15,
    MODE_VSCOM_CH = 16,
    MODE_VSCOM = 17,
    MODE_VSCOM_FL_NS = 18,
    MODE_VSCOM_FL_NE = 19,
    MODE_VSCOM_FL_CH = 20,
    MODE_VSCOM_FL = 21,
    MODE_PLAY2 = 22,
    MODE_VSMAN_NS = 23,
    MODE_VSMAN_NE = 24,
    MODE_VSMAN_CH = 25,
    MODE_VSMAN = 26,
    MODE_VSMAN_FL_NS = 27,
    MODE_VSMAN_FL_NE = 28,
    MODE_VSMAN_FL_CH = 29,
    MODE_VSMAN_FL = 30,
    MODE_VSMAN_TA_NS = 31,
    MODE_VSMAN_TA_NE = 32,
    MODE_VSMAN_TA_CH = 33,
    MODE_VSMAN_TA = 34,
    MODE_PLAY4 = 35,
    MODE_PLAY4_TYPE1 = 36,
    MODE_PLAY4_TYPE2 = 37,
    MODE_PLAY4_TYPE3 = 38,
    MODE_PLAY4_TYPE4 = 39,
    MODE_PLAY4_CH = 40,
    MODE_PLAY4_LV = 41,
    MODE_PLAY4_TB_CH = 42,
    MODE_PLAY4_TB_LV = 43,
    MODE_PLAY4_FL_CH = 44,
    MODE_PLAY4_FL_LV = 45,
    MODE_OPTION = 46,
    MODE_RECORD_MS = 47,
    MODE_RECORD_PLAY1 = 48,
    MODE_RECORD_ST = 49,
    MODE_RECORD_LS = 50,
    MODE_RECORD_LS_TQ = 51,
    MODE_RECORD_LS_TA = 52,
    MODE_RECORD_VC = 53,
    MODE_RECORD_VC_FL = 54,
    MODE_RECORD_PLAY2 = 55,
    MODE_RECORD_VM = 56,
    MODE_RECORD_VM_FL = 57,
    MODE_RECORD_VM_TA = 58,
    MODE_TUTORIAL = 59,
    MODE_CONT = 60,
    MODE_NAME_NS = 61,
    MODE_NAME = 62,
    MODE_NAME_NE = 63,
    MODE_NAME_NE2 = 64,
    MODE_NAME_DEL_YN = 65,
    MODE_NAME_DEL_MES = 66,
    MODE_BACKUP = 67,
    MODE_BACKUP_YN = 68,
    MODE_BACKUP_MES = 69,
    MODE_MISC = 70,
    MODE_SOUND = 71,
    MODE_COUNT = 72,
    MODE_SCORE = 73,
} @enum$856main_menu_c;
typedef enum /* @enum$1025main_menu_c */ {
    CURSOR_ITEM = 0,
    CURSOR_PANEL = 1,
    CURSOR_WINDOW = 2,
    CURSOR_THICK = 3,
    CURSOR_NEW_4P = 4,
    CURSOR_NEW_MUSIC = 5,
    CURSOR_NEW_SPEED = 6,
    CURSOR_NEW_VIRUS_LV_L = 7,
    CURSOR_NEW_VIRUS_LV_S = 8,
    CURSOR_TYPE_SUM = 9,
} @enum$1025main_menu_c;
typedef enum /* @enum$9657main_menu_c */ {
    RANK_FIG_NUMBER = 7,
    RANK_FIG_TIME = 8,
    RANK_FIG_RATIO = 9,
    RANK_FIG_LEVEL = 10,
    RANK_FIG_TIME2 = 11,
    RANK_FIG_CLEAR = 12,
    RANK_FIG_ALL = 13,
    RANK_FIG_SUM = 14,
} @enum$9657main_menu_c;
typedef enum /* @enum$165dm_manual_main_c */ {
    MODE_CAPSEL_PROC = 777,
    MODE_WAIT_MESSAGE = 778,
    MODE_WAIT_CAPSEL_FALL = 779,
    MODE_EXIT = 780,
} @enum$165dm_manual_main_c;
